# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-30 17:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('academic_year_code', models.IntegerField(primary_key=True, serialize=False)),
                ('academic_year', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('depratment_name', models.CharField(max_length=30)),
                ('inception_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Feedback.AcademicYear')),
            ],
        ),
    ]
