# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programstructure',
            name='subject_name',
            field=models.CharField(max_length=50),
        ),
    ]
