# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-08 09:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='home_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Feedback.Department'),
        ),
    ]
