# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-08 11:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback', '0002_auto_20170208_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursefeedbackassignment',
            name='course_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='CourseRegistration_course_code', to='Feedback.CourseRegistration'),
        ),
        migrations.AlterField(
            model_name='coursefeedbackassignment',
            name='cycle_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Feedback.FeedbackType'),
        ),
        migrations.AlterField(
            model_name='coursefeedbackassignment',
            name='student_reg_no',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='CourseRegistration_student_reg_no', serialize=False, to='Feedback.CourseRegistration'),
        ),
        migrations.AlterField(
            model_name='courseoffered',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Feedback.AcademicYear'),
        ),
        migrations.AlterField(
            model_name='courseoffered',
            name='faculty_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Feedback.Faculty'),
        ),
        migrations.AlterField(
            model_name='courseoffered',
            name='program_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='CO_PS_program_code', to='Feedback.ProgramStructure'),
        ),
        migrations.AlterField(
            model_name='courseoffered',
            name='regulation_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='CO_PS_regulation_code', to='Feedback.ProgramStructure'),
        ),
        migrations.AlterField(
            model_name='courseoffered',
            name='subject_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='CO_PS_subject_code', to='Feedback.ProgramStructure'),
        ),
        migrations.AlterField(
            model_name='courseregistration',
            name='course_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Feedback.CourseOffered'),
        ),
        migrations.AlterField(
            model_name='courseregistration',
            name='student_reg_no',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='Feedback.Student'),
        ),
        migrations.AlterField(
            model_name='department',
            name='inception_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Feedback.AcademicYear'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='home_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Feedback.Department'),
        ),
        migrations.AlterField(
            model_name='feedbackcommentlog',
            name='course_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Feedback.CourseOffered'),
        ),
        migrations.AlterField(
            model_name='feedbackcommentlog',
            name='cycle_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Feedback.FeedbackType'),
        ),
        migrations.AlterField(
            model_name='feedbackquestion',
            name='cycle_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Feedback.FeedbackType'),
        ),
        migrations.AlterField(
            model_name='feedbackratingaggregate',
            name='course_code',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='Feedback.CourseOffered'),
        ),
        migrations.AlterField(
            model_name='feedbackratingaggregate',
            name='cycle_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Feedback.FeedbackType'),
        ),
        migrations.AlterField(
            model_name='feedbackratinglog',
            name='course_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='FeedbackCommentLog_course_code', to='Feedback.FeedbackCommentLog'),
        ),
        migrations.AlterField(
            model_name='feedbackratinglog',
            name='cycle_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='FeedbackCommentLog_cycle_no', to='Feedback.FeedbackCommentLog'),
        ),
        migrations.AlterField(
            model_name='feedbackratinglog',
            name='feedback_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='FeedbackCommentLog_feedback_no', to='Feedback.FeedbackCommentLog'),
        ),
        migrations.AlterField(
            model_name='program',
            name='inception_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Feedback.AcademicYear'),
        ),
        migrations.AlterField(
            model_name='program',
            name='owner_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Feedback.Department'),
        ),
        migrations.AlterField(
            model_name='programstructure',
            name='program_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Feedback.Program'),
        ),
        migrations.AlterField(
            model_name='programstructure',
            name='regulation_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Feedback.Regulation'),
        ),
        migrations.AlterField(
            model_name='programstructure',
            name='subject_delivery_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Feedback.SubjectDeliveryType'),
        ),
        migrations.AlterField(
            model_name='programstructure',
            name='subject_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Feedback.SubjectType'),
        ),
        migrations.AlterField(
            model_name='student',
            name='academic_year_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Feedback.AcademicYear'),
        ),
        migrations.AlterField(
            model_name='student',
            name='regulation_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Feedback.Regulation'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Feedback.StudentType'),
        ),
        migrations.AlterField(
            model_name='subjectoption',
            name='offered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Feedback.Department'),
        ),
        migrations.AlterField(
            model_name='subjectoption',
            name='program_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='SO_PS_program_code', to='Feedback.ProgramStructure'),
        ),
        migrations.AlterField(
            model_name='subjectoption',
            name='regulation_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='SO_PS_regulation_code', to='Feedback.ProgramStructure'),
        ),
        migrations.AlterField(
            model_name='subjectoption',
            name='subject_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='SO_PS_subject_code', to='Feedback.ProgramStructure'),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Feedback.UserType'),
        ),
    ]
