# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-11 07:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback', '0002_auto_20170510_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseregistration',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='courseregistration',
            name='student_reg_no',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='Feedback.Student'),
        ),
    ]
