# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 14:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback', '0002_auto_20170719_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='programstructure',
            name='offered_by',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.PROTECT, to='Feedback.Department'),
            preserve_default=False,
        ),
    ]
