# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 15:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback', '0003_programstructure_offered_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseoffered',
            name='program_code',
        ),
        migrations.RemoveField(
            model_name='courseoffered',
            name='regulation_code',
        ),
    ]
