# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-19 11:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback', '0003_auto_20170208_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseoffered',
            name='program_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Feedback_program_code2', to='Feedback.ProgramStructure'),
        ),
        migrations.AlterField(
            model_name='courseoffered',
            name='regulation_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Feedback_regulation_code2', to='Feedback.ProgramStructure'),
        ),
        migrations.AlterField(
            model_name='courseoffered',
            name='subject_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Feedback_subject_code2', to='Feedback.ProgramStructure'),
        ),
        migrations.AlterField(
            model_name='subjectoption',
            name='program_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Feedback_program_code', to='Feedback.ProgramStructure'),
        ),
        migrations.AlterField(
            model_name='subjectoption',
            name='regulation_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Feedback_regulation_code', to='Feedback.ProgramStructure'),
        ),
        migrations.AlterField(
            model_name='subjectoption',
            name='subject_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Feedback_subject_code', to='Feedback.ProgramStructure'),
        ),
    ]
