# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback', '0004_auto_20170719_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursefeedbackassignment',
            name='feedback_weighting',
            field=models.IntegerField(default=1),
        ),
    ]
