# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-11 07:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback', '0005_auto_20170511_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseregistration',
            name='course_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Feedback.CourseOffered'),
        ),
        migrations.AlterUniqueTogether(
            name='courseregistration',
            unique_together=set([('course_code', 'student_reg_no')]),
        ),
    ]
