# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-11 08:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback', '0008_auto_20170511_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseregistration',
            name='auto_increment_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='courseregistration',
            name='course_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Feedback.CourseOffered'),
        ),
    ]
