# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-18 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback', '0009_auto_20170511_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackquestion',
            name='question_text',
            field=models.CharField(max_length=1000),
        ),
    ]
