# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 13:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback', '0011_auto_20170712_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursefeedbackassignment',
            name='course_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_code_set', to='Feedback.CourseRegistration'),
        ),
    ]
