# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 00:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback', '0012_auto_20170712_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackcommentlog',
            name='feedback_no',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
