# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 00:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback', '0013_auto_20170714_0559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedbackratingaggregate',
            old_name='Rating_1_count_1',
            new_name='rating_1_count_1',
        ),
        migrations.RenameField(
            model_name='feedbackratingaggregate',
            old_name='Rating_1_count_2',
            new_name='rating_1_count_2',
        ),
        migrations.RenameField(
            model_name='feedbackratingaggregate',
            old_name='Rating_2_count_1',
            new_name='rating_2_count_1',
        ),
        migrations.RenameField(
            model_name='feedbackratingaggregate',
            old_name='Rating_2_count_2',
            new_name='rating_2_count_2',
        ),
        migrations.RenameField(
            model_name='feedbackratingaggregate',
            old_name='Rating_3_count_1',
            new_name='rating_3_count_1',
        ),
        migrations.RenameField(
            model_name='feedbackratingaggregate',
            old_name='Rating_3_count_2',
            new_name='rating_3_count_2',
        ),
        migrations.RenameField(
            model_name='feedbackratingaggregate',
            old_name='Rating_4_count_1',
            new_name='rating_4_count_1',
        ),
        migrations.RenameField(
            model_name='feedbackratingaggregate',
            old_name='Rating_4_count_2',
            new_name='rating_4_count_2',
        ),
        migrations.RenameField(
            model_name='feedbackratingaggregate',
            old_name='Rating_5_count_1',
            new_name='rating_5_count_1',
        ),
        migrations.RenameField(
            model_name='feedbackratingaggregate',
            old_name='Rating_5_count_2',
            new_name='rating_5_count_2',
        ),
    ]
