# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-30 17:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rep1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Reporter1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='1', max_length=70)),
                ('age', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='rep1',
            name='fname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Reporter1'),
        ),
    ]
